#!/bin/zsh
# Modified sorin's theme
#

# Load dependencies
pmodload 'helper'

function prompt_hack_precmd {
   setopt LOCAL_OPTIONS
   unsetopt XTRACE KSH_ARRAYS

   if (( $+functions[git-info] )); then
      git-info
   fi

   [[ ! -n "$PROMPT_TITLE" ]] && {
      _HCK_CUSTOM=""
   } || {
      _HCK_CUSTOM="%F{blue}$PROMPT_TITLE ";
   }

   [[ "$TERM" == "linux" ]] || [[ -n "$PROMPT_TITLE" ]] || \
      echo -ne "\033]0;${PWD}\007"

   PROMPT="%F{white}%1~%f${git_info:+${(e)git_info[prompt]}} ${_HCK_CUSTOM}%(!.%B%F{red}#%f%b.%B%F{green}]%f%b) "
}

function prompt_hack_setup {
   setopt LOCAL_OPTIONS
   unsetopt XTRACE KSH_ARRAYS
   prompt_opts=(cr percent subst)

   autoload -Uz add-zsh-hook
   add-zsh-hook precmd prompt_hack_precmd

   zstyle ':prezto:module:editor' completing '%B%F{red}...%f%b'
   zstyle ':prezto:module:editor:keymap:primary' overwrite ' %F{red}F%f'
   zstyle ':prezto:module:editor:keymap' alternate ' %F{yellow}<%f%B%F{red}<%f%b%F{red}<%f '
   zstyle ':prezto:module:git' action ':%%B%F{yellow}%s%f%%b'
   zstyle ':prezto:module:git' added ' %%B%F{green}+%f%%b'
   zstyle ':prezto:module:git' ahead ' %%B%F{yellow}A%f%%b'
   zstyle ':prezto:module:git' behind ' %%B%F{yellow}B%f%%b'
   zstyle ':prezto:module:git' branch ':%F{red}%b%f'
   zstyle ':prezto:module:git' commit ':%F{green}%.7c%f'
   zstyle ':prezto:module:git' deleted ' %%B%F{red}X%f%%b'
   zstyle ':prezto:module:git' modified ' %%B%F{red}変%f%%b'
   zstyle ':prezto:module:git' position ':%F{green}%p%f'
   zstyle ':prezto:module:git' renamed ' %%B%F{magenta}R%f%%b'
   zstyle ':prezto:module:git' stashed ' %%B%F{cyan}*%f%%b'
   zstyle ':prezto:module:git' unmerged ' %%B%F{yellow}合%f%%b'
   zstyle ':prezto:module:git' untracked ' %%B%F{white}僥%f%%b'
   zstyle ':prezto:module:git' info \
      'prompt'  ' %F{cyan}git%f$(coalesce "%b" "%p" "%c")%s' \
      'rprompt' '%F{green}%A%B%S%a%d%m%r%U%u'

   RPROMPT='${editor_info[keymap]}${editor_info[overwrite]}%(?:: %f)${VIM:+" %B%F{green}V%f%b"}%F{green}[${git_info[rprompt]}%(?, %F{green}(⌐■_■), %F{yellow}%?%F{red}（╯°□°）╯ ┻━┻ )%f'
   SPROMPT='zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? '
}

prompt_hack_setup "$@"

