#!/bin/sh
# anime enviroiment
#
# needs: mlocate

# configuration
export _LIBANIME_ROOT="$HOME/lib/anime"         # root path to this library
export _LIBANIME_DB="$_LIBANIME_ROOT/locate.db" # locate.db for mlocate
export _LIBANIME_CACHE="$_LIBANIME_ROOT/cache"  # .afil, .adir for regexped cache
export _ANIME_SAVE_HISTORY=1                    # save history?
export _ANIME_SEED="seed"                       # seed directory
export _ANIME_WATCHING="watching"               # watching directory
export _ANIME_WATCHED="watched"                 # watched directory
export _ANIME_HISTORY="/tmp/.animehist"         # history list
export _ANIME_ROOT="/mnt/anime"                 # root of your animus

# alias for binaries
alias anime="__anime"
alias mkanime="$_LIBANIME_ROOT/bin/mkanime"
alias mvanime="$_LIBANIME_ROOT/bin/mvanime"
alias rsanime="$_LIBANIME_ROOT/bin/rsanime"

# wrapper for _anime
__anime() {
   "$_LIBANIME_ROOT/bin/anime" "$@"
   [[ $? -eq 0 ]] || return
   [[ $_ANIME_SAVE_HISTORY -eq 0 ]] || _anime_save_hist
}

# helper function
_anime_save_hist() {
   [[ "$(basename $SHELL)" == "zsh" ]] &&
      print -s "anime $(cat $_ANIME_HISTORY | tail -n1)"
   [[ "$(basename $SHELL)" == "bash" ]] &&
      history -s "anime $(cat $_ANIME_HISTORY | tail -n1)"
}
