#!/bin/sh
# anime enviroiment
#
# needs: mlocate

# configuration
export _LIBANIME_ROOT="$HOME/lib/anime"
export _LIBANIME_DB="$_LIBANIME_ROOT/cache.db"
export _ANIME_SAVE_HISTORY=1
export _ANIME_SEED="seed"
export _ANIME_WATCHING="watching"
export _ANIME_WATCHED="watched"
export _ANIME_HISTORY="/tmp/animehist"
export _ANIME_ROOT="/mnt/anime"

# alias for binaries
alias anime="__anime"
alias mkanime="$_LIBANIME_ROOT/bin/mkanime"
alias mvanime="$_LIBANIME_ROOT/bin/mvanime"
alias rsanime="$_LIBANIME_ROOT/bin/rsanime"

# wrapper for _anime
__anime() {
   "$_LIBANIME_ROOT/bin/anime" "$@"
   [[ $? -eq 0 ]] || return
   [[ $_ANIME_SAVE_HISTORY -eq 0 ]] || _anime_save_hist
}

# helper function
_anime_save_hist() {
   [[ "$(basename $SHELL)" == "zsh" ]] &&
      print -s "anime $(cat $_ANIME_HISTORY | tail -n1)"
   [[ "$(basename $SHELL)" == "bash" ]] &&
      history -s "anime $(cat $_ANIME_HISTORY | tail -n1)"
}
