#!/bin/bash
# toolsched library file

schedtool="$(which --skip-alias --skip-functions schedtool 2>&1)"
ionice="$(which --skip-alias --skip-functions ionice 2>&1)"

# Launch process
toolsched_launch()
{
   local cmd="$(basename $0)"
   local command=
   for i in $(which --skip-alias --skip-functions -a "$cmd" 2>&1); do
      if [[ "$i" != "$0" ]]; then
         command="$i"
         break
      fi
   done

   if [[ ! -n "$command" ]]; then
      echo "$cmd: command not found [$command, $0]"
      exit 1
   fi

   exec "$command" "$@"
   exit $?
}

# Set current process to idle
toolsched_idle()
{
   # SCHED_IDLEPRIO
   $schedtool -D $$ >/dev/null 2>&1

   # IDLE
   $ionice -c3 -p$$ >/dev/null 2>&1
}

# Set current process to iso
toolsched_iso()
{
   # SCHED_ISO
   $schedtool -I $$ >/dev/null 2>&1

   # BEST-EFFORT
   $ionice -c2 -n0 -p$$ >/dev/null 2>&1
}

# Set current process to batch
toolsched_batch()
{
   # SCHED_BATCH
   $schedtool -B $$ >/dev/null 2>&1
}
