#!/bin/sh
# toolsched enviroiment file

[[ "$PATH" == */arch/toolsched/bin* ]] || {
   which schedtool &> /dev/null && {
      export PATH="/arch/toolsched/bin:$PATH"
   } || echo "WARN: schedtool not found, skipping toolsched enviroiment."
}
