#!/bin/sh
# Systemwide shell aliases
#

# coreutils aliases
alias ls='ls++'
alias dir='dir -h --color=auto'
alias vdir='vdir -h --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias du='du -sh'
alias df='df -h'

# interactive coreutils
alias cp='cp -v'
alias mv='mv -v'
alias rm='rm -v'
alias ln='ln -v'

# less with ansi escapes
alias less='less -R'

# quick vim less alias
local VLESS="$(find /usr/share/vim -name 'less.sh')"
[[ -n "$VLESS" ]] && alias vl="$VLESS"

# bell alias
alias bell='echo \\007\\c'

# unmount wrapper
alias um='udevil --umount'

# mpd client aliases
alias  lm='lolimpd'
alias   m='lolimpdnu'
alias lmr='sort -R /tmp/lolimpdnu.cache | head -n1 | sed "s/.*\t//" | xargs lolimpd play'

# neat git log
alias sgl='git log --decorate --pretty=oneline --abbrev-commit --graph'

# vidir alias
alias vd='vidir'

# view image in clipboard
alias cim='xcmenu -b image/png > /tmp/clipboard.png && { sxiv /tmp/clipboard.png; rm /tmp/clipboard.png; }'

# get extrenal ip
alias extip='curl -s http://icanhazip.com'

# vim support
alias  :w='echo this is a shell, not vim.'
alias :wq=:w
alias  :q='exit'

# pacmatic wrapper
alias pacman='pacmatic'
alias      q='/usr/bin/pacman -Q'
alias      r='sudo pacmatic -Rsn'
alias      s='sudo pacmatic -S'
alias    ssp='sspacman'
alias      u='sudo pacmatic -Syu'

# shortcuts
alias -- +='sudo'
alias -- -='less'
alias   \?='egrep'
alias  z\?='zegrep'
alias    ~='sed'
alias    @='cat'
alias   z@='zcat'
