#!/bin/sh
# Systemwide shell aliases
#

# coreutils aliases
alias ls='ls++'
alias dir='dir -h --color=auto'
alias vdir='vdir -h --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias du='du -sh'
alias df='df -h'

# interactive coreutils
alias cp='cp -v'
alias mv='mv -v'
alias rm='rm -v'
alias ln='ln -v'

# vim support
alias :w='echo this is a shell, not vim.'
alias :wq=:w
alias :q='exit'

# pacmatic wrapper
alias pacman='pacmatic'
alias q='/usr/bin/pacman -Q'
alias r='sudo pacmatic -Rsn'
alias s='sudo pacmatic -S'
alias ss='sspacman'
alias u='sudo pacmatic -Syu'

# mpd client aliases
alias m='ncmpc'
alias lm='lolimpd'

# view image in clipboard
alias cim='loliclip -b image/png > /tmp/clipboard.png && { sxiv /tmp/clipboard.png; rm /tmp/clipboard.png; }'

# shorter sudo
alias -- +='sudo'

# get extrenal ip
alias extip='echo $(curl -s http://automation.whatismyip.com/n09230945.asp)'
