#!/bin/bash
# bash and zsh complicant rc source

################################
## Test for interactive shell ##
################################
[[ "$-" == *i* ]] || return

#########################
## SSH complicant mode ##
#########################
[[ -n "$SSH_TTY" ]] && export TERM="linux"

###########################
## Enviroiment Variables ##
###########################

# Default programs
export EDITOR="vim"
export BROWSER="chromium"
export TERMINAL="termite"

# SDL
export SDL_AUDIODRIVER="alsa"
export SDL_VIDEO_FULLSCREEN_HEAD=1

# JAVA
export _JAVA_AWT_WM_NONREPARENTING=1

# GTK
export GDK_USE_XFT=1

# Check if everything is broken
[[ -z "$LANG" ]] && eval "$(locale)"

# Set XDG variables
[[ -n "$XDG_CACHE_HOME" ]] || export XDG_CACHE_HOME="$HOME/.cache"
[[ -n "$XDG_CONFIG_HOME" ]] || export XDG_CONFIG_HOME="$HOME/.config"
[[ -n "$XDG_DATA_HOME" ]] || export XDG_DATA_HOME="$HOME/.local/share"

# Global override path
# ($HOME/bin && /arch/bin)
[[ "$PATH" == *$HOME/bin* ]] && [[ "$PATH" == */arch/bin* ]] ||
   export PATH="$HOME/bin:/arch/bin:$PATH"

# Ccache
[[ "$PATH" == */usr/lib/ccache/bin* ]] ||
   export PATH="/usr/lib/ccache/bin:$PATH"

# Make ccache use compilers from this path
export CCACHE_PATH="/usr/bin"
export CCACHE_DIR="/arch/ccache"

# Source passwd enviroiment
source "/arch/passwd/libpasswd-env"

# Source toolsched enviroiment
source "/arch/toolsched/toolsched-env"

# LS_COLORS
# https://github.com/trapd00r/LS_COLORS
eval $(dircolors -b "/arch/shell/LS_COLORS")

# Welcome text
echo "Welcome to lolified Arch Linux"
echo "\ts   - pacman -S"
echo "\tssp - pacman -Ss"
echo "\tq   - pacman -Q"
echo "\tr   - pacman -Rsn"
echo "\tu   - pacman -Syu"
echo "\t+   - sudo"
echo "\t-   - less"
echo "\t@   - cat"
echo "\t?   - grep"
echo "\t~   - sed"
echo "\nYou are running intelligent clipboard daemon"
echo "which is integrated with dmenu and monsterwm."
echo "All your XA_CLIPBOARD (ctrl-c) clips are synced"
echo "with XA_PRIMARY (shift-ins) automatically."
echo "\tmeta-c\t\t- access clipboard history"
echo "\tmeta-shift-c\t- access url history from clipboard"
echo "\talt-shift-c\t- synchorize XA_PRIMARY to XA_CLIPBOARD"
echo "\nDo 'less /arch/README' to remind what you have done to me."
echo "\nAll modified system wide configurations,"
echo "AUR packages and other related reside in /arch\n"

#########################################
# Change prompt name                    #
# NOTE: prezto themes need to           #
# be modified to work with PROMPT_TITLE #
#########################################
function tname() {
   echo -ne "\033]0;${@:-$PWD}\007";
   PROMPT_TITLE=${@:-""}
}

# If root, set default prompt title
[[ "$(whoami)" == "root" ]] && \
   export PROMPT_TITLE="root"
