#!/bin/sh
# bash and zsh complicant rc source

################################
## Test for interactive shell ##
################################
[[ "$-" == *i* ]] || return

#########################
## SSH complicant mode ##
#########################
[[ -n "$SSH_TTY" ]] && export TERM="linux"

###########################
## Enviroiment Variables ##
###########################

# Default programs
export EDITOR="vim"
export BROWSER="dwb"

# Fix weird urxvt bugs on su, ssh
[[ "$TERM" == *rxvt* ]] && export TERM="xterm-256color"

# Better sorting
export LC_ALL=
export LC_COLLATE="C"

# SDL
export SDL_AUDIODRIVER="alsa"
export SDL_VIDEO_FULLSCREEN_HEAD=1

# JAVA
export _JAVA_AWT_WM_NONREPARENTING=1

# GTK
export GDK_USE_XFT=1

# Global override path
# ($HOME/bin && /arch/bin)
[[ "$PATH" == *$HOME/bin* ]] && [[ "$PATH" == */arch/bin* ]] ||
   export PATH="$HOME/bin:/arch/bin:$PATH"

# Ccache
[[ "$PATH" == */usr/lib/ccache/bin* ]] ||
   export PATH="/usr/lib/ccache/bin:$PATH"

# Colored gcc
[[ "$PATH" == */usr/lib/colorgcc/bin* ]] ||
   export PATH="/usr/lib/colorgcc/bin:$PATH"

# Make ccache use compilers from this path
export CCACHE_PATH="/usr/bin"
export CCACHE_DIR="/arch/ccache"

# Vim as less
VLESS="$(find /usr/share/vim -name 'less.sh')"
[[ -n "$VLESS" ]] && alias less="$VLESS"

# Source passwd enviroiment
source "/arch/passwd/libpasswd-env"

# Source toolsched enviroiment
source "/arch/toolsched/toolsched-env"

# LS_COLORS
# https://github.com/trapd00r/LS_COLORS
eval $( dircolors -b /arch/shell/LS_COLORS )

# Welcome text
echo "Welcome to lolified Arch Linux"
echo "\ts  - pacman -S"
echo "\tss - pacman -Ss"
echo "\tq  - pacman -Q"
echo "\tr  - pacman -Rsn"
echo "\tu  - pacman -Syu"
echo "\t+  - sudo"
echo "\nYou are running intelligent clipboard daemon"
echo "which is integrated with dmenu and monsterwm."
echo "All your XA_CLIPBOARD (ctrl-c) clips are synced"
echo "with XA_PRIMARY (shift-ins) automatically."
echo "\tmeta-c\t\t- access clipboard history"
echo "\tmeta-shift-c\t- access url history from clipboard"
echo "\talt-shift-c\t- synchorize XA_PRIMARY to XA_CLIPBOARD"
echo "\nDo 'less /arch/README' to remind what you have done to me."
echo "\nAll modified system wide configurations,"
echo "AUR packages and other related reside in /arch"

#########################################
# Change prompt name                    #
# NOTE: oh-my-zsh themes need to        #
# be modified to work with PROMPT_TITLE #
#########################################
function tname() {
   echo -ne "\033]0;${@:-$PWD}\007";
   PROMPT_TITLE=${@:-""}
}
