#
# Systemwide zshrc
#

# source global shell file
# (tests for interactive shell)
source "/arch/shell/shellrc"

# execute in background
{
   # compile the completion dump to increase startup speed.
   dump_file="$HOME/.zcompdump"
   if [[ "$dump_file" -nt "${dump_file}.zwc" || ! -s "${dump_file}.zwc" ]]; then
      zcompile "$dump_file"
   fi
} &!

# prezto
export OMZ="/arch/shell/prezto"

# other enviroiment crap
typeset -gU cdpath fpath mailpath manpath path
typeset -gUT INFOPATH infopath

# GNU info
infopath=(
   /usr/local/share/info
   /usr/share/info
   $infopath
)

# man
manpath=(
   /usr/local/share/man
   /usr/share/man
   $manpath
)

# add paths from /etc/manpaths.d as well
for path_file in /etc/manpaths.d/*(.N); do
   manpath+=($(<$path_file))
done
unset path_file

# zmv
autoload -U zmv

# ssh-agent forwarding
zstyle ':omz:plugins:ssh-agent' forwarding 'on'

# Set the key mapping style to 'emacs' or 'vi'.
zstyle ':omz:module:editor' keymap 'vi'

# Auto convert .... to ../..
zstyle ':omz:module:editor' dot-expansion 'no'

# Set case-sensitivity for completion, history lookup, etc.
zstyle ':omz:*:*' case-sensitive 'no'

# Color output (auto set to 'no' on dumb terminals).
zstyle ':omz:*:*' color 'yes'

# don't show $PWD in ../
zstyle ':completion:*' ignore-parents 'pwd'

# ignore commands I don't have
zstyle ':completion:*:functions' ignored-patterns '(_*|pre(cmd|exec))'

# Syntax hilight
zstyle ':omz:module:syntax-highlighting' highlighters \
   'main' \
   'brackets' \
   'pattern' \
   'root'

# Set the Oh My Zsh modules to load (browse modules).
# The order matters.
zstyle ':omz:load' omodule \
   'environment' \
   'editor' \
   'history' \
   'directory' \
   'spectrum' \
   'utility' \
   'completion' \
   'ssh-agent' \
   'git' \
   'syntax-highlighting' \
   'prompt'

# set prompt
zstyle ':omz:module:prompt' theme 'hack'

# launch
source "$OMZ/init.zsh"

# link completitions
compdef pacmatic=pacman

# source functions and aliases
source "/arch/shell/functions"
source "/arch/shell/alias"

# zsh options
unsetopt correct # I can't see why people like this
                 # stop typing wrong silly people
bindkey "\e[1~"   beginning-of-line    # Home
bindkey "^A"      beginning-of-line    # CTRL+A
bindkey "\e[4~"   end-of-line          # End
bindkey "\e[5~"   beginning-of-history # PageUp
bindkey "\e[6~"   end-of-history       # PageDown
bindkey "\e[2~"   quoted-insert        # Ins
bindkey "\e[3~"   delete-char          # Del
bindkey "\e[5C"   forward-word
bindkey "\eOc"    emacs-forward-word
bindkey "\e[5D"   backward-word
bindkey "\eOd"    emacs-backward-word
bindkey "\e\e[C"  forward-word
bindkey "\e\e[D"  backward-word
bindkey "\e[Z"    reverse-menu-complete # Shift+Tab
bindkey "\e[7~"   beginning-of-line     # Home
bindkey "\e[8~"   end-of-line           # End
bindkey "\eOH"    beginning-of-line
bindkey "\eOF"    end-of-line
bindkey "^I"      menu-complete         # Why press tab twice?
bindkey "^Z"      undo                  # Undo
bindkey '^R' history-incremental-search-backward
